title: WWT Docs Hub
email: wwt@aas.org
description: >-
  The hub for documentation relating to the AAS WorldWide Telescope.
twitter_username: wwtelescope
github_username: WorldWideTelescope
remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md # canonical version is in `worldwidetelescope.github.io`
