title: AAS WorldWide Telescope Documentation Hub
email: wwt@aas.org
description: >-
  The hub for documentation relating to the AAS WorldWide Telescope.
twitter_username: wwtelescope
github_username: WorldWideTelescope
theme: just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
